// "metadata";
"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Provider } from "react-redux";
import store from "./store/store";
// import "../assets/js/browser_scripttage.js"
// import "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
// import "../assets/js/bootstrap.min.js"
// import "../assets/js/custom.js"
// import "../assets/js/iziToast.min.js"
// import "../assets/js/common.js"
// import "../assets/js/lozad.min.js"

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Shreeji App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://example.com/script.js" />
      <body className={inter.className}>
      <Provider store={store}>
        {children}
        </Provider>
        </body>
    </html>
  );
}

// "use client";
// import { Inter } from 'next/font/google'
// import './globals.css'

// import { useEffect } from 'react'

// const inter = Inter({ subsets: ['latin'] })

// export default function RootLayout({ children }) {

//     useEffect(() => {
//       if (typeof window !== "undefined") {
//         const link = document.createElement('link');
//         link.href = 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap';
//         link.href = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
//         link.rel = 'stylesheet';
//         document.head.appendChild(link);
//       }
//     }, [])

//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
